### ISSUE TITLE
Command list time field problem

### ISSUE THREAD

**Issue by alexpouliquen** [Digital-Design/Foyer#4]
On http://foyer.p4ul.tk/api/command/login/:login
Time field contain date + time instead of only time

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order

**Comment by thecampagnards** [comment]
time = date + hour when you ordered
date = date when you want to recover your order
